### ISSUE TITLE
Stable Diffusion Version

### ISSUE THREAD

**Issue by adeerAI** [byeongjun-park/HarmonyView#6]
Hi there,

Thank you for the wonderful repository, I wanted to know which Stable Diffusion version is used for the multi-view generation. And, can we use safetensor checkpoint files for generation.

Regards

**Comment by byeongjun-park** [comment]
Hi, @adeerAI

We use the pre-trained model provided by the SyncDreamer repo.

This model is fine-tuned from the stable diffusion with a few layers added.

The ckpt file is provided through our Google Drive [(link)](https://drive.google.com/drive/folders/1hWfTlG1yMlPlKCkeYL4_1lqJN1-aG1GJ), and the safetensor ckpt file is not available at this time.

Thank you for your understanding.

**Comment by adeerAI** [comment]
I searched through syncdreamer paper but couldn't analyze which stable diffusion version they are using. Also, have you tried with different neus reconstruction models such as neurangelo, etc?

**Comment by byeongjun-park** [comment]
In my opinion, SyncDreamer seems like using the image-conditioned diffusion model (version 2) provided by [lambdalabs](https://huggingface.co/spaces/lambdalabs/stable-diffusion-image-variations). This model has been fine-tuned to accept CLIP image embedding rather than text embedding from [stable-diffusion-v-1-4-original](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original).

We are also planning to work on a faster NeuS (i.e., NeuS2), which can generate 3D content faster than neurangelo. At the moment, it's unclear when it will be completed as we have a lot of other work to do.
